package com.frontdash.dao;

public enum MessageType {
    RESTAURANT_REGISTRATION_APPROVAL,
    RESTAURANT_APPROVAL_REJECTION,
    RESTAURANT_WITHDRAWAL_APPROVAL,
    RESTAURANT_WITHDRAWAL_REJECTION,
    RESTAURANT_WITHDRAWAL_REQUEST,
    STAFF_ACCOUNT_CREDENTIALS_SHARING,
    RESTAURANT_ACCOUNT_CREATION_CREDENTIALS_SHARING
}
